name: Release

on:
  push:
    tags: [ "v*" ]

jobs:
  build-release:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Build
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_FILE: keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: calnotify
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > "$KEYSTORE_FILE"
          nix develop -c just build-release

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/app-release.apk
            build/*.pbw
          generate_release_notes: true
